services:
  imageserver:
    image: shelland/image-server:latest
    restart: always
    volumes:
      - /tmp:/tmp
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:5000"